title: Guilhem SCHLOSSER
logo: /assets/img/headshot_circle.jpg
description: Python Programming | Data Science | GenAI & LLM | Machine Learning | Machine Translation
show_downloads: False
theme: jekyll-theme-minimal
