During my internship at the ERTIM (INALCO) research unit specializing in NLP, I identified, analyzed, and monitored Chinese narratives across newspapers using structural semantics (Actantial model) and NLP tools (LLM and BERTopic).
